import { ProjectPage, TerminalStrip } from '@/types/electrical';

export const INITIAL_PAGES: ProjectPage[] = [
  {
    id: 'page_01',
    pageNumber: 1,
    title: 'Diagrama Unifilar Geral QGBT (Alimentadores & Proteção)',
    code: 'E-01/04',
    category: 'UNIFILAR',
    format: 'A3',
    orientation: 'LANDSCAPE',
    titleBlock: {
      projectTitle: 'EletricAI - CCM-01 Agroindústria Copacol',
      clientName: 'Copacol Agroindústria — Planta Cafelândia',
      engineerName: 'Eng. Luis Felipe',
      creaNumber: 'CREA-PR 88.412/D',
      date: '23/09/2026',
      revision: 'REV B',
      scale: '1:1',
      sheetNumber: '01',
      totalSheets: 4,
      approvedBy: 'Coord. Engenharia',
      standardReference: 'ABNT NBR 5410 / NBR 14039 / IEC 60947',
    },
  },
  {
    id: 'page_02',
    pageNumber: 2,
    title: 'Diagrama Multifilar de Potência (3F+PE 380V)',
    code: 'E-02/04',
    category: 'MULTIFILAR_POWER',
    format: 'A3',
    orientation: 'LANDSCAPE',
    titleBlock: {
      projectTitle: 'EletricAI - CCM-01 Agroindústria Copacol',
      clientName: 'Copacol Agroindústria — Planta Cafelândia',
      engineerName: 'Eng. Luis Felipe',
      creaNumber: 'CREA-PR 88.412/D',
      date: '23/09/2026',
      revision: 'REV B',
      scale: '1:1',
      sheetNumber: '02',
      totalSheets: 4,
      approvedBy: 'Coord. Engenharia',
      standardReference: 'ABNT NBR 5410 / IEC 60204-1',
    },
  },
  {
    id: 'page_03',
    pageNumber: 3,
    title: 'Diagrama Multifilar de Comando 24VDC & Intertravamento',
    code: 'E-03/04',
    category: 'MULTIFILAR_COMMAND',
    format: 'A3',
    orientation: 'LANDSCAPE',
    titleBlock: {
      projectTitle: 'EletricAI - CCM-01 Agroindústria Copacol',
      clientName: 'Copacol Agroindústria — Planta Cafelândia',
      engineerName: 'Eng. Luis Felipe',
      creaNumber: 'CREA-PR 88.412/D',
      date: '23/09/2026',
      revision: 'REV B',
      scale: '1:1',
      sheetNumber: '03',
      totalSheets: 4,
      approvedBy: 'Coord. Engenharia',
      standardReference: 'ABNT NBR 5410 / NR-10 / NR-12',
    },
  },
  {
    id: 'page_04',
    pageNumber: 4,
    title: 'Régua de Bornes, Lista de Cabos e Tabela de Cargas',
    code: 'E-04/04',
    category: 'TERMINALS',
    format: 'A3',
    orientation: 'LANDSCAPE',
    titleBlock: {
      projectTitle: 'EletricAI - CCM-01 Agroindústria Copacol',
      clientName: 'Copacol Agroindústria — Planta Cafelândia',
      engineerName: 'Eng. Luis Felipe',
      creaNumber: 'CREA-PR 88.412/D',
      date: '23/09/2026',
      revision: 'REV B',
      scale: '1:1',
      sheetNumber: '04',
      totalSheets: 4,
      approvedBy: 'Coord. Engenharia',
      standardReference: 'ABNT NBR 5410 / IEC 61439',
    },
  },
];

export const INITIAL_TERMINAL_STRIPS: TerminalStrip[] = [
  {
    id: 'strip_x1',
    tag: '-X1',
    name: 'Régua Principal de Potência e Comando CCM-01',
    panelTag: 'CCM-01',
    terminals: [
      { id: 't1', terminalNumber: '1', type: 'PASS_THROUGH', wireInTag: 'L1', wireOutTag: 'U1', fromDeviceTag: 'FT01', toDeviceTag: 'MTR01', wireGaugeMm2: 16, pageRef: 'E-02/04' },
      { id: 't2', terminalNumber: '2', type: 'PASS_THROUGH', wireInTag: 'L2', wireOutTag: 'V1', fromDeviceTag: 'FT01', toDeviceTag: 'MTR01', wireGaugeMm2: 16, pageRef: 'E-02/04' },
      { id: 't3', terminalNumber: '3', type: 'PASS_THROUGH', wireInTag: 'L3', wireOutTag: 'W1', fromDeviceTag: 'FT01', toDeviceTag: 'MTR01', wireGaugeMm2: 16, pageRef: 'E-02/04' },
      { id: 't4', terminalNumber: 'PE', type: 'PE_GROUND', wireInTag: 'PE', wireOutTag: 'PE_MTR', fromDeviceTag: 'BARRA_PE', toDeviceTag: 'MTR01_CARC', wireGaugeMm2: 16, isBridgeConnected: true, pageRef: 'E-02/04' },
      { id: 't5', terminalNumber: '11', type: 'PASS_THROUGH', wireInTag: '+24V', wireOutTag: '+24V_EXT', fromDeviceTag: 'FONTE_24V', toDeviceTag: 'BTN_EMERG', wireGaugeMm2: 1.5, pageRef: 'E-03/04' },
      { id: 't6', terminalNumber: '12', type: 'PASS_THROUGH', wireInTag: '%I0.0', wireOutTag: 'S_EMERG', fromDeviceTag: 'PLC_DI0', toDeviceTag: 'BTN_EMERG_NF', wireGaugeMm2: 1.5, pageRef: 'E-03/04' },
      { id: 't7', terminalNumber: '13', type: 'PASS_THROUGH', wireInTag: '%I0.2', wireOutTag: 'S_LIGA', fromDeviceTag: 'PLC_DI2', toDeviceTag: 'BTN_LIGA_NA', wireGaugeMm2: 1.5, pageRef: 'E-03/04' },
      { id: 't8', terminalNumber: '14', type: 'PASS_THROUGH', wireInTag: '%I0.3', wireOutTag: 'S_DESL', fromDeviceTag: 'PLC_DI3', toDeviceTag: 'BTN_DESL_NF', wireGaugeMm2: 1.5, pageRef: 'E-03/04' },
      { id: 't9', terminalNumber: '15', type: 'PASS_THROUGH', wireInTag: '%Q0.2', wireOutTag: 'K1_A1', fromDeviceTag: 'PLC_DO2', toDeviceTag: 'KM01_A1', wireGaugeMm2: 1.5, pageRef: 'E-03/04' },
      { id: 't10', terminalNumber: '16', type: 'NEUTRAL_N', wireInTag: '0VDC', wireOutTag: '0V_RET', fromDeviceTag: 'FONTE_0V', toDeviceTag: 'KM01_A2', wireGaugeMm2: 1.5, isBridgeConnected: true, pageRef: 'E-03/04' },
    ],
  },
];
