import { IndustrialProject, IndustrialAlert, ActivityEvent, TeamMember, SystemNotification } from '@/types/dashboard';

export const INITIAL_PROJECTS: IndustrialProject[] = [
  {
    id: 'proj_ccm_01',
    name: 'CCM-01 Planta Moagem & Compressão',
    code: 'EAI-PRJ-2024-001',
    type: 'CCM_BT',
    typeLabel: 'Centro de Controle de Motores (BT)',
    status: 'EM_EXECUCAO',
    progressPercent: 85,
    lastUpdated: 'Hoje às 15:42',
    lastUpdatedTimestamp: Date.now() - 1000 * 60 * 38,
    updatedBy: {
      name: 'Eng. Luis Felipe',
      role: 'admin',
      creaNumber: 'CREA-PR 88.412/D',
    },
    nominalVoltage: '380V / 220V - 60 Hz',
    normativeStandard: 'ABNT NBR 5410',
    targetTab: 'unifilar',
    description: 'Painel TTA/PTTA com alimentadores gaveta para compressores e moinhos de martelo.',
  },
  {
    id: 'proj_se_02',
    name: 'Subestação SE-02 13.8kV/380V Industrial',
    code: 'EAI-PRJ-2024-002',
    type: 'SUBESTACAO_MT',
    typeLabel: 'Subestação Abrigada MT/BT',
    status: 'EM_COMISSIONAMENTO',
    progressPercent: 92,
    lastUpdated: 'Hoje às 11:20',
    lastUpdatedTimestamp: Date.now() - 1000 * 60 * 290,
    updatedBy: {
      name: 'Engª. Mariana Souza',
      role: 'engineer',
      creaNumber: 'CREA-SP 142.901/D',
    },
    nominalVoltage: '13.8 kV / 380V - 60 Hz',
    normativeStandard: 'ABNT NBR 14039',
    targetTab: 'unifilar',
    description: 'Transformador a óleo 1500 kVA com proteção de sobrecorrente temporizada 50/51.',
  },
  {
    id: 'proj_aut_linha03',
    name: 'Automação Linha de Envase & Paletização',
    code: 'EAI-PRJ-2024-003',
    type: 'AUTOMACAO_CLP',
    typeLabel: 'Automação & CLP IEC 61131-3',
    status: 'EM_EXECUCAO',
    progressPercent: 68,
    lastUpdated: 'Ontem às 18:05',
    lastUpdatedTimestamp: Date.now() - 1000 * 60 * 60 * 23,
    updatedBy: {
      name: 'Téc. Carlos Eduardo',
      role: 'member',
    },
    nominalVoltage: '24V DC / 220V AC',
    normativeStandard: 'NR-10',
    targetTab: 'ladder',
    description: 'Lógica sequencial em Ladder com rungs intertravados por barreira de luz de segurança.',
  },
  {
    id: 'proj_qgbt_04',
    name: 'Quadro QGBT-Geral Almoxarifado Central',
    code: 'EAI-PRJ-2024-004',
    type: 'QGBT_DISTRIBUICAO',
    typeLabel: 'Quadro Geral de Baixa Tensão',
    status: 'CONCLUIDO',
    progressPercent: 100,
    lastUpdated: '18 Set 2024',
    lastUpdatedTimestamp: Date.now() - 1000 * 60 * 60 * 96,
    updatedBy: {
      name: 'Eng. Luis Felipe',
      role: 'admin',
      creaNumber: 'CREA-PR 88.412/D',
    },
    nominalVoltage: '380V / 220V - 60 Hz',
    normativeStandard: 'ABNT NBR 5410',
    targetTab: 'bom',
    description: 'Projeto as-built homologado com memorial de cálculo de queda de tensão em 2.8%.',
  },
];

export const INITIAL_ALERTS: IndustrialAlert[] = [
  {
    id: 'alert_01',
    title: 'Queda de Tensão Crítica no Alimentador Q02',
    description: 'Queda calculada de 4.8% no circuito do compressor de 75CV excede o limite normativo de 4.0% para circuitos terminais.',
    severity: 'CRITICO',
    category: 'NBR_5410',
    timestamp: 'Há 12 minutos',
    sourceTag: 'Q02_COMPRESSOR',
    componentId: 'comp_q02',
    targetTab: 'unifilar',
    suggestedAction: 'Aumentar seção do condutor de 16mm² para 25mm² ou readequar trajeto.',
    isResolved: false,
  },
  {
    id: 'alert_02',
    title: 'Dispositivo Remoto I/O Subestação Offline',
    description: 'Timeout na resposta Modbus TCP no endereço 192.168.10.45 após 3 tentativas de handshake de varredura.',
    severity: 'CRITICO',
    category: 'MODBUS_REDE',
    timestamp: 'Há 35 minutos',
    sourceTag: 'RIO_SUBESTACAO',
    targetTab: 'scada',
    suggestedAction: 'Verificar alimentação 24Vdc da fonte e integridade do cabo de par trançado.',
    isResolved: false,
  },
  {
    id: 'alert_03',
    title: 'Inconsistência de Coordenação Térmica no Rung 02',
    description: 'Contato NF do relé térmico FT01 não possui intertravamento no circuito de retenção da bobina K01.',
    severity: 'ATENCAO',
    category: 'CLP_IO',
    timestamp: 'Há 1 hora',
    sourceTag: 'FT01_TERMIC_COMP',
    targetTab: 'ladder',
    suggestedAction: 'Inserir contato normalmente fechado (%I0.1) em série com a bobina (%Q0.2).',
    isResolved: false,
  },
  {
    id: 'alert_04',
    title: 'Dispositivo DPS sem Indicação de Desconexão',
    description: 'Protetor contra surtos classe II no QGBT sem contato auxiliar de sinalização remota de queima.',
    severity: 'RECOMENDACAO',
    category: 'SEGURANCA_NR10',
    timestamp: 'Há 3 horas',
    targetTab: 'bom',
    suggestedAction: 'Especificar cartucho DPS com contato reversor para telemetria SCADA.',
    isResolved: false,
  },
  {
    id: 'alert_05',
    title: 'Disjuntor de Entrada Q01 Re-armado com Sucesso',
    description: 'Trip anterior por sobrecarga térmica sanado após redistribuição de cargas na barra B1.',
    severity: 'RESOLVIDO',
    category: 'SOBRECARGA',
    timestamp: 'Hoje às 09:15',
    sourceTag: 'Q01_GERAL',
    targetTab: 'unifilar',
    suggestedAction: 'Nenhuma ação pendente. Corrente de regime normalizada em 312A.',
    isResolved: true,
  },
];

export const INITIAL_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act_01',
    type: 'AI_ANALYSIS_EXECUTED',
    title: 'Análise de Conformidade NBR 5410 Executada',
    description: 'IA Copilot identificou conformidade em 14 dos 15 circuitos do CCM-01.',
    timestamp: 'Há 18 minutos',
    user: { name: 'IA Copilot EletricAI', role: 'engineer' },
    badgeColor: 'text-amber-400 border-amber-500/30 bg-amber-500/10',
    targetTab: 'ai_copilot',
  },
  {
    id: 'act_02',
    type: 'PROJECT_UPDATED',
    title: 'Circuito Q02 Atualizado para Partida Estrela-Triângulo',
    description: 'Substituição de partida direta por contator auxiliar K02 com temporizador TON 5s.',
    timestamp: 'Há 45 minutos',
    user: { name: 'Eng. Luis Felipe', role: 'admin' },
    badgeColor: 'text-cyan-400 border-cyan-500/30 bg-cyan-500/10',
    targetTab: 'unifilar',
  },
  {
    id: 'act_03',
    type: 'REPORT_GENERATED',
    title: 'BOM & Memorial Descritivo Exportado em PDF/Excel',
    description: 'Orçamento de materiais no padrão ABNT gerado totalizando R$ 148.650,00.',
    timestamp: 'Há 2 horas',
    user: { name: 'Engª. Mariana Souza', role: 'engineer' },
    badgeColor: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10',
    targetTab: 'bom',
  },
  {
    id: 'act_04',
    type: 'PROJECT_EXPORTED',
    title: 'Projeto Unifilar Exportado em AutoCAD DXF',
    description: 'Camadas de barramento, proteção, cabos e tags exportadas com sucesso.',
    timestamp: 'Hoje às 13:10',
    user: { name: 'Eng. Luis Felipe', role: 'admin' },
    badgeColor: 'text-purple-400 border-purple-500/30 bg-purple-500/10',
    targetTab: 'unifilar',
  },
  {
    id: 'act_05',
    type: 'MEMBER_ADDED',
    title: 'Novo Engenheiro Adicionado à Equipe da Planta',
    description: 'Eng. Rafael Guimarães integrado com permissões de Engenheiro de Automação.',
    timestamp: 'Ontem às 16:30',
    user: { name: 'Eng. Luis Felipe', role: 'admin' },
    badgeColor: 'text-blue-400 border-blue-500/30 bg-blue-500/10',
  },
  {
    id: 'act_06',
    type: 'BREAKER_TRIP',
    title: 'Simulação de Trip por Sobrecarga Térmica Registrada',
    description: 'Disjuntor motor Q02 operou a 1.25x In durante teste de estresse de comissionamento.',
    timestamp: 'Ontem às 14:15',
    user: { name: 'Téc. Carlos Eduardo', role: 'member' },
    badgeColor: 'text-rose-400 border-rose-500/30 bg-rose-500/10',
    targetTab: 'digital_twin',
  },
];

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: 'team_01',
    name: 'Eng. Luis Felipe',
    email: 'luis.felipe@copacol.ind.br',
    role: 'admin',
    roleTitle: 'Engenheiro Eletricista Sênior',
    creaNumber: 'CREA-PR 88.412/D',
    status: 'ONLINE',
    lastActive: 'Agora',
    avatarInitials: 'LF',
  },
  {
    id: 'team_02',
    name: 'Engª. Mariana Souza',
    email: 'mariana.souza@copacol.ind.br',
    role: 'engineer',
    roleTitle: 'Engenheiro de Automação',
    creaNumber: 'CREA-SP 142.901/D',
    status: 'ONLINE',
    lastActive: 'Há 5 minutos',
    avatarInitials: 'MS',
  },
  {
    id: 'team_03',
    name: 'Téc. Carlos Eduardo',
    email: 'carlos.eduardo@copacol.ind.br',
    role: 'member',
    roleTitle: 'Técnico em Eletrotécnica',
    creaNumber: 'CFT-PR 33.109/TD',
    status: 'EM_CAMPO',
    lastActive: 'Há 32 minutos',
    avatarInitials: 'CE',
  },
  {
    id: 'team_04',
    name: 'Eng. Rafael Guimarães',
    email: 'rafael.g@copacol.ind.br',
    role: 'engineer',
    roleTitle: 'Coordenador de Manutenção',
    creaNumber: 'CREA-PR 91.802/D',
    status: 'ONLINE',
    lastActive: 'Há 12 minutos',
    avatarInitials: 'RG',
  },
  {
    id: 'team_05',
    name: 'Luciana Mendes',
    email: 'luciana.mendes@copacol.ind.br',
    role: 'admin',
    roleTitle: 'Administrador da Planta',
    status: 'OFFLINE',
    lastActive: 'Ontem às 18:40',
    avatarInitials: 'LM',
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif_01',
    title: 'Alerta Crítico: Queda de Tensão NBR 5410',
    message: 'Circuito Q02 com 4.8% ΔV ultrapassou o patamar máximo de 4.0%.',
    timestamp: 'Há 12 min',
    isRead: false,
    type: 'ALERT',
    targetTab: 'unifilar',
  },
  {
    id: 'notif_02',
    title: 'Nova Proposta de Patch da IA Disponível',
    message: 'Correção automática de fiação e retificação de seção de cabos pronta para revisão.',
    timestamp: 'Há 25 min',
    isRead: false,
    type: 'AI_PATCH',
    targetTab: 'ai_copilot',
  },
  {
    id: 'notif_03',
    title: 'Memorial de Cálculo Aprovado',
    message: 'Projeto Subestação SE-02 certificado para emissão de ART.',
    timestamp: 'Há 2h',
    isRead: true,
    type: 'REPORT',
    targetTab: 'bom',
  },
];
