import { PlcProgramConfiguration, PlcVariable, IoModuleConfig } from '@/types/plc';

export const INITIAL_PLC_VARIABLES: PlcVariable[] = [
  // Digital Inputs (%I)
  {
    id: 'var_btn_emerg',
    name: 'BTN_EMERGENCIA',
    dataType: 'BOOL',
    address: '%I0.0',
    initialValue: true,
    currentValue: true,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Botoeira tipo Cogumelo Parada de Emergência NR-10/NR-12 (NF)',
    description: 'Circuito de segurança geral de comando do painel CCM-01',
    unifilarComponentTag: 'SUB_MT_13.8KV',
  },
  {
    id: 'var_ft01',
    name: 'FT01_TERMIC_COMP',
    dataType: 'BOOL',
    address: '%I0.1',
    initialValue: true,
    currentValue: true,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Contato auxiliar 95-96 do Relé Térmico do Compressor (NF)',
    description: 'Proteção contra sobrecarga do motor de 30 CV MTR01',
    unifilarComponentTag: 'FT01_COMPRESSOR',
  },
  {
    id: 'var_btn_start',
    name: 'BTN_PARTIDA_COMP',
    dataType: 'BOOL',
    address: '%I0.2',
    initialValue: false,
    currentValue: false,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Botoeira Pulsadora Liga Compressor KM01 (NA)',
    description: 'Comando de partida manual local no painel',
  },
  {
    id: 'var_btn_stop',
    name: 'BTN_PARADA_COMP',
    dataType: 'BOOL',
    address: '%I0.3',
    initialValue: true,
    currentValue: true,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Botoeira Pulsadora Desliga Compressor KM01 (NF)',
    description: 'Comando de parada operacional manual',
  },
  {
    id: 'var_sensor_press_min',
    name: 'SENSOR_PRESS_MIN',
    dataType: 'BOOL',
    address: '%I0.4',
    initialValue: true,
    currentValue: true,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Pressostato Digital Pressão Mínima Rede (NA)',
    description: 'Detecta pressão de ar comprimido acima de 6.0 bar',
  },

  // Digital Outputs (%Q)
  {
    id: 'var_q01_geral',
    name: 'Q01_GERAL',
    dataType: 'BOOL',
    address: '%Q0.0',
    initialValue: true,
    currentValue: true,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Bobina de Disparo/Liberação Disjuntor Geral 630A',
    description: 'Alimentação do barramento principal de 800A',
    unifilarComponentTag: 'Q01_GERAL',
  },
  {
    id: 'var_km01_comp',
    name: 'KM01_COMPRESSOR',
    dataType: 'BOOL',
    address: '%Q0.2',
    initialValue: true,
    currentValue: true,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Contator Principal Partida Compressor 30 CV',
    description: 'Alimenta o estator do motor W22 de moagem',
    unifilarComponentTag: 'KM01_COMPRESSOR',
  },
  {
    id: 'var_km02_estrela',
    name: 'KM02_ESTRELA',
    dataType: 'BOOL',
    address: '%Q0.3',
    initialValue: false,
    currentValue: false,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Contator de Fechamento em Estrela (Y)',
    description: 'Reduz corrente de partida para 1/3 da nominal',
  },
  {
    id: 'var_km03_triang',
    name: 'KM03_TRIANGULO',
    dataType: 'BOOL',
    address: '%Q0.4',
    initialValue: true,
    currentValue: true,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Contator de Regime Pleno em Triângulo (Δ)',
    description: 'Opera o compressor sob torque e rotação nominais',
  },
  {
    id: 'var_lamp_alarme',
    name: 'LAMP_ALARME_FALHA',
    dataType: 'BOOL',
    address: '%Q0.7',
    initialValue: false,
    currentValue: false,
    isForced: false,
    isRetentive: false,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Sinalizador Audiovisual de Falha Geral no CCM',
    description: 'Torre de sinalização luminosa vermelha piscante',
  },

  // Internal Memories & Analogs (%M, %MD)
  {
    id: 'var_pressao_ar',
    name: 'PRESSAO_REDE_AR',
    dataType: 'REAL',
    address: '%MD10',
    initialValue: 7.42,
    currentValue: 7.42,
    isForced: false,
    isRetentive: true,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Pressão Hidráulica / Pneumática da Rede Principal',
    description: 'Faixa operacional: 6.0 a 8.5 bar',
    unit: 'bar',
    engineeringMin: 0,
    engineeringMax: 16,
  },
  {
    id: 'var_temp_comp',
    name: 'TEMP_MANCAL_COMP',
    dataType: 'REAL',
    address: '%MD14',
    initialValue: 64.5,
    currentValue: 64.5,
    isForced: false,
    isRetentive: true,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Temperatura do Mancal de Rolamento Compressor',
    description: 'Sensor PT-100 4-20mA no rolamento dianteiro',
    unit: '°C',
    engineeringMin: 0,
    engineeringMax: 150,
  },
  {
    id: 'var_horimetro',
    name: 'HORIMETRO_OPERACIONAL',
    dataType: 'DINT',
    address: '%MD20',
    initialValue: 1420,
    currentValue: 1420,
    isForced: false,
    isRetentive: true,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Horímetro Total de Horas de Operação Acumuladas',
    description: 'Horímetro mantido em memória retentiva NVRAM (RETAIN)',
    unit: 'h',
  },
  {
    id: 'var_ciclo_cont',
    name: 'CONTADOR_PARTIDAS',
    dataType: 'INT',
    address: '%MW30',
    initialValue: 84,
    currentValue: 84,
    isForced: false,
    isRetentive: true,
    isConstant: false,
    scope: 'VAR_GLOBAL',
    comment: 'Número de partidas registradas no turno atual',
    description: 'Contador IEC CTU',
  },
];

export const INITIAL_PLC_MODULES: IoModuleConfig[] = [
  {
    id: 'mod_0',
    slotNumber: 0,
    name: 'Fonte de Alimentação Industrial 24VDC 10A',
    catalogNumber: 'WEG-PS24V-10A',
    type: 'POWER_SUPPLY',
    status: 'OK',
    channels: [],
  },
  {
    id: 'mod_1',
    slotNumber: 1,
    name: 'CPU EletricAI Dual-Core Real-Time IEC 61131-3',
    catalogNumber: 'EAI-CPU-900',
    type: 'CPU',
    status: 'OK',
    channels: [],
  },
  {
    id: 'mod_2',
    slotNumber: 2,
    name: 'Módulo de 16 Entradas Digitais 24VDC Optoisoladas',
    catalogNumber: 'EAI-DI16-24V',
    type: 'DI_16',
    status: 'OK',
    channels: [
      { id: 'ch_di_0', channelIndex: 0, address: '%I0.0', name: 'Canal 00', tag: 'BTN_EMERGENCIA', type: 'DI', state: true, description: 'Botoeira Emergência (NF)' },
      { id: 'ch_di_1', channelIndex: 1, address: '%I0.1', name: 'Canal 01', tag: 'FT01_TERMIC_COMP', type: 'DI', state: true, description: 'Relé Térmico Compressor (NF)' },
      { id: 'ch_di_2', channelIndex: 2, address: '%I0.2', name: 'Canal 02', tag: 'BTN_PARTIDA_COMP', type: 'DI', state: false, description: 'Botão Partida (NA)' },
      { id: 'ch_di_3', channelIndex: 3, address: '%I0.3', name: 'Canal 03', tag: 'BTN_PARADA_COMP', type: 'DI', state: true, description: 'Botão Parada (NF)' },
      { id: 'ch_di_4', channelIndex: 4, address: '%I0.4', name: 'Canal 04', tag: 'SENSOR_PRESS_MIN', type: 'DI', state: true, description: 'Pressostato Mínimo' },
      { id: 'ch_di_5', channelIndex: 5, address: '%I0.5', name: 'Canal 05', tag: '', type: 'DI', state: false, description: 'Reserva' },
      { id: 'ch_di_6', channelIndex: 6, address: '%I0.6', name: 'Canal 06', tag: '', type: 'DI', state: false, description: 'Reserva' },
      { id: 'ch_di_7', channelIndex: 7, address: '%I0.7', name: 'Canal 07', tag: '', type: 'DI', state: false, description: 'Reserva' },
    ],
  },
  {
    id: 'mod_3',
    slotNumber: 3,
    name: 'Módulo de 16 Saídas Digitais a Relé 230VAC 2A',
    catalogNumber: 'EAI-DO16-REL',
    type: 'DO_16',
    status: 'OK',
    channels: [
      { id: 'ch_do_0', channelIndex: 0, address: '%Q0.0', name: 'Canal 00', tag: 'Q01_GERAL', type: 'DO', state: true, description: 'Disjuntor Geral 630A' },
      { id: 'ch_do_1', channelIndex: 1, address: '%Q0.1', name: 'Canal 01', tag: '', type: 'DO', state: false, description: 'Reserva' },
      { id: 'ch_do_2', channelIndex: 2, address: '%Q0.2', name: 'Canal 02', tag: 'KM01_COMPRESSOR', type: 'DO', state: true, description: 'Contator Compressor' },
      { id: 'ch_do_3', channelIndex: 3, address: '%Q0.3', name: 'Canal 03', tag: 'KM02_ESTRELA', type: 'DO', state: false, description: 'Partida Estrela Y' },
      { id: 'ch_do_4', channelIndex: 4, address: '%Q0.4', name: 'Canal 04', tag: 'KM03_TRIANGULO', type: 'DO', state: true, description: 'Regime Triângulo Δ' },
      { id: 'ch_do_5', channelIndex: 5, address: '%Q0.5', name: 'Canal 05', tag: '', type: 'DO', state: false, description: 'Reserva' },
      { id: 'ch_do_6', channelIndex: 6, address: '%Q0.6', name: 'Canal 06', tag: '', type: 'DO', state: false, description: 'Reserva' },
      { id: 'ch_do_7', channelIndex: 7, address: '%Q0.7', name: 'Canal 07', tag: 'LAMP_ALARME_FALHA', type: 'DO', state: false, description: 'Torre de Alarme' },
    ],
  },
  {
    id: 'mod_4',
    slotNumber: 4,
    name: 'Módulo de 8 Entradas Analógicas 4-20mA / PT-100 16-Bit',
    catalogNumber: 'EAI-AI8-HART',
    type: 'AI_8',
    status: 'OK',
    channels: [
      { id: 'ch_ai_0', channelIndex: 0, address: '%IW64', name: 'Canal 00', tag: 'PRESSAO_REDE_AR', type: 'AI', rangeMin: 0, rangeMax: 16, unit: 'bar', state: 7.42, description: 'Transmissor Pressão Linha' },
      { id: 'ch_ai_1', channelIndex: 1, address: '%IW66', name: 'Canal 01', tag: 'TEMP_MANCAL_COMP', type: 'AI', rangeMin: 0, rangeMax: 150, unit: '°C', state: 64.5, description: 'Sensor PT-100 Mancal' },
    ],
  },
];

export const INITIAL_PLC_PROGRAM_CONFIG: PlcProgramConfiguration = {
  id: 'plc_proj_ccm01',
  projectName: 'CCM-01 Automação Planta de Moagem & Compressão',
  standardReference: 'IEC 61131-3:2025',
  version: '2.4.0',
  author: 'Eng. Luis Felipe / Engª. Beatriz Lima',
  revision: 'Rev 03',
  date: '2026-09-23',
  comments: 'Sistema de automação com controle de intertravamentos de segurança e ciclo de partida Estrela-Triângulo.',
  scanTimeMs: 12,
  actualScanTimeMs: 1.45,
  cycleCount: 14820,
  executionMode: 'SIMULATION',
  executionStatus: 'RUN',
  activePouId: 'pou_main_ld',

  rack: {
    id: 'rack_01',
    rackName: 'RACK_CENTRAL_CCM',
    chassisModel: 'EletricAI S7-Edge Modular',
    ipAddress: '192.168.10.20',
    subnetMask: '255.255.255.0',
    cycleTimeTargetMs: 12,
    modules: INITIAL_PLC_MODULES,
  },

  globalVariables: INITIAL_PLC_VARIABLES,

  pous: [
    {
      id: 'pou_main_ld',
      name: 'Main_Control_Logic',
      type: 'PROGRAM',
      language: 'LD',
      description: 'Lógica Principal de Controle de Potência e Segurança NR-10/NR-12',
      version: '1.2.0',
      author: 'Eng. Luis Felipe',
      dateCreated: '2026-01-15',
      lastModified: '2026-09-23',
      revision: 4,
      localVariables: [
        {
          id: 'lvar_aux_flag',
          name: 'LOC_SELO_ATIVO',
          dataType: 'BOOL',
          initialValue: false,
          currentValue: true,
          isForced: false,
          isRetentive: false,
          isConstant: false,
          scope: 'VAR_LOCAL',
          comment: 'Flag de estado local de auto-retenção',
        },
      ],
      rungs: [
        {
          id: 'rung_ld_0',
          rungNumber: 0,
          title: 'Linha de Segurança Geral & Emergência NR-10/NR-12',
          description: 'Desliga imediatamente a alimentação primária caso o botão de emergência seja acionado ou haja trip térmico.',
          comment: 'Condição segura: BTN_EMERGENCIA (NF) = 1 e FT01_TERMIC_COMP (NF) = 1.',
          isEnabled: true,
          isPowerFlowActive: true,
          diagnosticStatus: 'NORMAL',
          elements: [
            {
              id: 'el_r0_1',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NO',
              variableName: 'BTN_EMERGENCIA',
              address: '%I0.0',
              row: 0,
              col: 0,
              isEnergized: true,
              comment: 'Botão Emergência',
            },
            {
              id: 'el_r0_2',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NO',
              variableName: 'FT01_TERMIC_COMP',
              address: '%I0.1',
              row: 0,
              col: 1,
              isEnergized: true,
              comment: 'Relé Térmico Normal Fechado',
            },
            {
              id: 'el_r0_3',
              elementType: 'COIL',
              coilType: 'COIL_NORMAL',
              variableName: 'Q01_GERAL',
              address: '%Q0.0',
              row: 0,
              col: 5,
              isEnergized: true,
              comment: 'Bobina Geral 630A',
            },
          ],
        },
        {
          id: 'rung_ld_1',
          rungNumber: 1,
          title: 'Comando de Partida com Selo (Start/Stop) Compressor KM01',
          description: 'Lógica padrão industrial de auto-retenção do contator principal KM01 com botão desliga prioritário.',
          comment: 'Ramo paralelo: BTN_PARTIDA_COMP (col 0, row 0) ou Selo KM01_COMPRESSOR (col 0, row 1).',
          isEnabled: true,
          isPowerFlowActive: true,
          diagnosticStatus: 'NORMAL',
          elements: [
            {
              id: 'el_r1_1',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NO',
              variableName: 'BTN_PARTIDA_COMP',
              address: '%I0.2',
              row: 0,
              col: 0,
              isEnergized: false,
              comment: 'Botão Liga',
            },
            {
              id: 'el_r1_selo',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NO',
              variableName: 'KM01_COMPRESSOR',
              address: '%Q0.2',
              row: 1,
              col: 0,
              isEnergized: true,
              comment: 'Contato de Selo (Auto-retenção)',
            },
            {
              id: 'el_r1_2',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NO',
              variableName: 'BTN_PARADA_COMP',
              address: '%I0.3',
              row: 0,
              col: 1,
              isEnergized: true,
              comment: 'Botão Desliga (NF)',
            },
            {
              id: 'el_r1_3',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NO',
              variableName: 'Q01_GERAL',
              address: '%Q0.0',
              row: 0,
              col: 2,
              isEnergized: true,
              comment: 'Intertravamento Disjuntor Geral',
            },
            {
              id: 'el_r1_4',
              elementType: 'COIL',
              coilType: 'COIL_NORMAL',
              variableName: 'KM01_COMPRESSOR',
              address: '%Q0.2',
              row: 0,
              col: 5,
              isEnergized: true,
              comment: 'Bobina Contator Principal',
            },
          ],
        },
        {
          id: 'rung_ld_2',
          rungNumber: 2,
          title: 'Temporizador de Transição Estrela-Triângulo IEC TON (T#6s)',
          description: 'Conta 6 segundos com motor em estrela antes de comutar para o contator de triângulo para aliviar Ipartida.',
          comment: 'Ativa bloco IEC 61131-3 TON. Ao término de PT (6s), a saída Q é energizada.',
          isEnabled: true,
          isPowerFlowActive: true,
          diagnosticStatus: 'NORMAL',
          elements: [
            {
              id: 'el_r2_1',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NO',
              variableName: 'KM01_COMPRESSOR',
              address: '%Q0.2',
              row: 0,
              col: 0,
              isEnergized: true,
              comment: 'Habilitação da Temporização',
            },
            {
              id: 'el_r2_ton',
              elementType: 'TIMER',
              timerType: 'TON',
              timerInstance: 'TON_Partida_YD',
              variableName: 'TON_Partida_YD',
              presetTimeMs: 6000,
              elapsedTimeMs: 6000,
              timerQ: true,
              row: 0,
              col: 2,
              isEnergized: true,
              comment: 'Temporizador On-Delay 6s',
            },
            {
              id: 'el_r2_3',
              elementType: 'COIL',
              coilType: 'COIL_NORMAL',
              variableName: 'KM03_TRIANGULO',
              address: '%Q0.4',
              row: 0,
              col: 5,
              isEnergized: true,
              comment: 'Bobina Regime Triângulo',
            },
          ],
        },
        {
          id: 'rung_ld_3',
          rungNumber: 3,
          title: 'Sinalização e Lógica de Trip Sobrecarga Térmica (NR-10)',
          description: 'Aciona a torre audiovisual e o alarme sonoro quando o relé térmico FT01 abrir seus contatos.',
          comment: 'Contato Normal Fechado —[/]— conduz quando FT01_TERMIC_COMP = 0 (falha).',
          isEnabled: true,
          isPowerFlowActive: false,
          diagnosticStatus: 'NORMAL',
          elements: [
            {
              id: 'el_r3_1',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NC',
              variableName: 'FT01_TERMIC_COMP',
              address: '%I0.1',
              row: 0,
              col: 0,
              isEnergized: false,
              comment: 'Alarme na abertura do térmico',
            },
            {
              id: 'el_r3_2',
              elementType: 'COIL',
              coilType: 'COIL_SET',
              variableName: 'LAMP_ALARME_FALHA',
              address: '%Q0.7',
              row: 0,
              col: 5,
              isEnergized: false,
              comment: 'Memoriza Falha (SET)',
            },
          ],
        },
        {
          id: 'rung_ld_4',
          rungNumber: 4,
          title: 'Comparador de Monitoramento de Pressão Mínima (> 6.0 bar)',
          description: 'Compara a variável analógica PRESSAO_REDE_AR com o setpoint mínimo permitido para operação segura.',
          comment: 'Bloco de Comparação Analógica IEC (GT: > 6.0 bar).',
          isEnabled: true,
          isPowerFlowActive: true,
          diagnosticStatus: 'NORMAL',
          elements: [
            {
              id: 'el_r4_comp',
              elementType: 'COMPARE',
              compareOp: 'GT',
              variableName: 'PRESSAO_REDE_AR',
              in1Value: 7.42,
              in2Value: 6.0,
              row: 0,
              col: 0,
              isEnergized: true,
              comment: 'Pressão > 6.0 bar',
            },
            {
              id: 'el_r4_coil',
              elementType: 'COIL',
              coilType: 'COIL_NORMAL',
              variableName: 'SENSOR_PRESS_MIN',
              address: '%I0.4',
              row: 0,
              col: 5,
              isEnergized: true,
              comment: 'Status Pressão Conforme',
            },
          ],
        },
      ],
    },
    {
      id: 'pou_pumps_ld',
      name: 'Pump_Reserve_Interlock',
      type: 'PROGRAM',
      language: 'LD',
      description: 'Lógica de Intertravamento e Transição Automática de Bomba Reserva',
      version: '1.0.0',
      author: 'Engª. Beatriz Lima',
      dateCreated: '2026-03-10',
      lastModified: '2026-09-23',
      revision: 2,
      localVariables: [],
      rungs: [
        {
          id: 'rung_pump_0',
          rungNumber: 0,
          title: 'Intertravamento Bomba Principal & Reserva',
          description: 'Impede o acionamento simultâneo e assume a reserva caso a primária apresente desarme.',
          comment: 'Intertravamento elétrico e lógico por software.',
          isEnabled: true,
          isPowerFlowActive: true,
          diagnosticStatus: 'NORMAL',
          elements: [
            {
              id: 'el_p0_1',
              elementType: 'CONTACT',
              contactType: 'CONTACT_NO',
              variableName: 'Q01_GERAL',
              address: '%Q0.0',
              row: 0,
              col: 0,
              isEnergized: true,
              comment: 'Habilitador Geral',
            },
            {
              id: 'el_p0_2',
              elementType: 'COIL',
              coilType: 'COIL_NORMAL',
              variableName: 'KM02_ESTRELA',
              address: '%Q0.3',
              row: 0,
              col: 5,
              isEnergized: false,
              comment: 'Standby Ativo',
            },
          ],
        },
      ],
    },
  ],

  interlocks: [
    {
      id: 'int_01',
      sourceTag: 'KM01_COMPRESSOR',
      targetTag: 'KM02_ESTRELA',
      condition: 'BLOCKS',
      description: 'KM02 (Estrela) e KM03 (Triângulo) possuem intertravamento elétrico e lógico mútuo contra curto-circuito.',
    },
    {
      id: 'int_02',
      sourceTag: 'BTN_EMERGENCIA',
      targetTag: 'Q01_GERAL',
      condition: 'TRIPS',
      description: 'Acionamento do botão cogumelo abre instantaneamente a bobina de mínima do disjuntor Q01.',
    },
    {
      id: 'int_03',
      sourceTag: 'FT01_TERMIC_COMP',
      targetTag: 'KM01_COMPRESSOR',
      condition: 'STANDBY_SWITCH',
      description: 'Sobrecarga no motor bloqueia nova partida até rearme manual conforme NR-10.',
    },
  ],

  alarms: [
    {
      id: 'alm_01',
      tag: 'FT01_TERMIC_COMP',
      condition: 'FT01 == FALSE',
      priority: 'CRITICAL',
      isActive: false,
      timestamp: '2026-09-23 09:12:00',
      description: 'Sobrecarga Térmica no Compressor de Moagem (Relé 95-96 aberto)',
    },
    {
      id: 'alm_02',
      tag: 'PRESSAO_REDE_AR',
      condition: 'PRESSAO_REDE_AR < 6.0',
      priority: 'HIGH',
      isActive: false,
      timestamp: '2026-09-23 08:30:15',
      description: 'Subpressão na Rede Principal de Ar Comprimido',
    },
    {
      id: 'alm_03',
      tag: 'TEMP_MANCAL_COMP',
      condition: 'TEMP_MANCAL_COMP > 75.0',
      priority: 'MEDIUM',
      isActive: false,
      timestamp: '2026-09-23 10:04:22',
      description: 'Temperatura elevada no rolamento dianteiro do motor',
    },
  ],

  recipes: [
    {
      id: 'rcp_01',
      name: 'Receita Moagem Alta Carga',
      parameters: {
        TEMPO_ESTRELA_SEC: 6,
        PRESSAO_SETPOINT_BAR: 7.8,
        LIMITE_CORRENTE_A: 48.0,
      },
    },
    {
      id: 'rcp_02',
      name: 'Receita Operação Econômica (Standby)',
      parameters: {
        TEMPO_ESTRELA_SEC: 4,
        PRESSAO_SETPOINT_BAR: 6.8,
        LIMITE_CORRENTE_A: 35.0,
      },
    },
  ],
};
