import {
  Tenant,
  UserProfile,
  SharedTag,
  ElectricalComponent,
  ElectricalConnection,
  LadderRung,
  FbdBlock,
  FbdWire,
  PlcRackConfig,
  ScadaWidget,
  DigitalTwinHotspot,
  BomItem,
} from '@/types/electrical';

export const INITIAL_TENANT: Tenant = {
  id: 'tenant_copacol_01',
  name: 'Copacol Agroindústria — Planta Cafelândia',
  cnpj: '76.093.738/0001-88',
  location: 'Cafelândia - PR, Brasil',
  plan: 'Enterprise Multi-Plant',
  currency: 'BRL',
};

export const INITIAL_USER: UserProfile = {
  id: 'usr_eng_luis',
  name: 'Eng. Luis Felipe',
  email: 'luis.felipe@copacol.ind.br',
  role: 'admin',
  creaNumber: 'CREA-PR 88.412/D',
  tenantId: 'tenant_copacol_01',
};

// SHARED TAG ENGINE - Core single source of truth across all modules
export const INITIAL_SHARED_TAGS: SharedTag[] = [
  {
    id: 'tag_btn_emerg',
    name: 'BTN_EMERGENCIA',
    description: 'Botão Cogumelo de Parada de Emergência NR-10/NR-12',
    address: '%I0.0',
    dataType: 'BOOL',
    direction: 'INPUT',
    currentValue: true, // NF (Normalmente Fechado quando seguro)
    unit: 'State',
  },
  {
    id: 'tag_ft01_trip',
    name: 'FT01_TERMIC_COMP',
    description: 'Contato Auxiliar do Relé Térmico Compressor (95-96)',
    address: '%I0.1',
    dataType: 'BOOL',
    direction: 'INPUT',
    currentValue: true, // NF
    unit: 'State',
  },
  {
    id: 'tag_btn_partida',
    name: 'BTN_PARTIDA_COMP',
    description: 'Botoeira Liga Compressor (Pulsador NA)',
    address: '%I0.2',
    dataType: 'BOOL',
    direction: 'INPUT',
    currentValue: false,
    unit: 'Pulse',
  },
  {
    id: 'tag_btn_parada',
    name: 'BTN_PARADA_COMP',
    description: 'Botoeira Desliga Compressor (Pulsador NF)',
    address: '%I0.3',
    dataType: 'BOOL',
    direction: 'INPUT',
    currentValue: true,
    unit: 'State',
  },
  {
    id: 'tag_q01_geral',
    name: 'Q01_GERAL',
    description: 'Disjuntor Caixa Moldada Entrada Geral CCM-01 (630A)',
    address: '%Q0.0',
    dataType: 'BOOL',
    direction: 'OUTPUT',
    currentValue: true,
    unit: 'Closed',
    circuitId: 'cct_main_bus',
    linkedComponentId: 'comp_q01',
  },
  {
    id: 'tag_q02_comp',
    name: 'Q02_COMPRESSOR',
    description: 'Disjuntor Caixa Moldada Circuito 01 - Compressor Parafuso 30cv',
    address: '%Q0.1',
    dataType: 'BOOL',
    direction: 'OUTPUT',
    currentValue: true,
    unit: 'Closed',
    circuitId: 'cct_comp_01',
    linkedComponentId: 'comp_q02',
  },
  {
    id: 'tag_km01_comp',
    name: 'KM01_COMPRESSOR',
    description: 'Bobina Contator Principal K1 Motor Compressor 30cv',
    address: '%Q0.2',
    dataType: 'BOOL',
    direction: 'OUTPUT',
    currentValue: true,
    unit: 'Energized',
    circuitId: 'cct_comp_01',
    linkedComponentId: 'comp_km01',
  },
  {
    id: 'tag_km02_estrela',
    name: 'KM02_ESTRELA',
    description: 'Bobina Contator Estrela K2 (Partida Y-D)',
    address: '%Q0.3',
    dataType: 'BOOL',
    direction: 'OUTPUT',
    currentValue: false,
    unit: 'Energized',
  },
  {
    id: 'tag_km03_triang',
    name: 'KM03_TRIANGULO',
    description: 'Bobina Contator Triângulo K3 (Regime Y-D)',
    address: '%Q0.4',
    dataType: 'BOOL',
    direction: 'OUTPUT',
    currentValue: true,
    unit: 'Energized',
  },
  {
    id: 'tag_q03_exaustor',
    name: 'Q03_EXAUSTOR',
    description: 'Disjuntor-Motor Exaustor Ventilação Filtro Manga 10cv',
    address: '%Q0.5',
    dataType: 'BOOL',
    direction: 'OUTPUT',
    currentValue: true,
    unit: 'Closed',
    circuitId: 'cct_exh_02',
    linkedComponentId: 'comp_q03',
  },
  {
    id: 'tag_km04_exaustor',
    name: 'KM04_EXAUSTOR',
    description: 'Bobina Contator Exaustor 10cv',
    address: '%Q0.6',
    dataType: 'BOOL',
    direction: 'OUTPUT',
    currentValue: true,
    unit: 'Energized',
  },
  {
    id: 'tag_lamp_alarme',
    name: 'LAMP_ALARME_FALHA',
    description: 'Sinalizador Audiovisual de Trip / Sobrecarga NR-10',
    address: '%Q0.7',
    dataType: 'BOOL',
    direction: 'OUTPUT',
    currentValue: false,
    unit: 'Beacon',
  },
  {
    id: 'tag_temp_mancl',
    name: 'TEMP_MANCAL_COMP',
    description: 'Transmissor de Temperatura PT100 Rolamento Mancal A',
    address: '%IW64',
    dataType: 'REAL',
    direction: 'ANALOG_IN',
    currentValue: 64.8,
    unit: '°C',
    alarmHigh: 85.0,
    alarmLow: 10.0,
    isAlarmActive: false,
  },
  {
    id: 'tag_press_ar',
    name: 'PRESSAO_REDE_AR',
    description: 'Transmissor de Pressão Reservatório Principal 0-16 bar',
    address: '%IW66',
    dataType: 'REAL',
    direction: 'ANALOG_IN',
    currentValue: 7.42,
    unit: 'bar',
    alarmHigh: 9.5,
    alarmLow: 5.0,
    isAlarmActive: false,
  },
  {
    id: 'tag_corrente_r',
    name: 'CORRENTE_FASE_R',
    description: 'Medidor Multimedidor Fase R Alimentador Q02',
    address: '%IW68',
    dataType: 'REAL',
    direction: 'ANALOG_IN',
    currentValue: 41.6,
    unit: 'A',
    alarmHigh: 55.0,
    isAlarmActive: false,
  },
  {
    id: 'tag_tmr_yd',
    name: 'TMR_STAR_DELTA',
    description: 'Temporizador IEC TON Transição Estrela-Triângulo',
    address: '%T01',
    dataType: 'TIME',
    direction: 'INTERNAL',
    currentValue: 6.0,
    unit: 's',
  },
];

// INITIAL UNIFILAR SCHEMATIC COMPONENTS (NBR 5410 / NBR 14039)
export const INITIAL_COMPONENTS: ElectricalComponent[] = [
  {
    id: 'comp_sub_mt',
    tag: 'SUB_MT_13.8KV',
    name: 'Subestação Primária 13.8 kV',
    category: 'SOURCE_MT',
    x: 100,
    y: 50,
    width: 140,
    height: 70,
    voltage: 13800,
    nominalCurrent: 200,
    power: 1000,
    breakingCapacity: 16,
    isEnergized: true,
    ports: [
      { id: 'p_sub_out', type: 'out', x: 170, y: 120 }
    ],
    manufacturer: 'Schneider Electric',
    partNumber: 'SM6-24kV Cubicle',
    unitCostBrl: 42000,
    statusText: 'Energizado 13.8kV NBR 14039',
  },
  {
    id: 'comp_trafo_01',
    tag: 'TR01_1000KVA',
    name: 'Transformador a Óleo 1000 kVA',
    category: 'TRANSFORMER_MT_BT',
    x: 100,
    y: 170,
    width: 140,
    height: 90,
    voltage: 380,
    nominalCurrent: 1519,
    power: 1000,
    powerFactor: 0.92,
    efficiency: 0.98,
    isEnergized: true,
    ports: [
      { id: 'p_tr_in', type: 'in', x: 170, y: 170 },
      { id: 'p_tr_out', type: 'out', x: 170, y: 260 }
    ],
    manufacturer: 'WEG',
    partNumber: 'Trafo 1000kVA 13.8/0.38-0.22kV',
    unitCostBrl: 78500,
    statusText: '13.8kV / 380-220V 60Hz',
  },
  {
    id: 'comp_q01',
    tag: 'Q01_GERAL',
    name: 'Disjuntor Geral Caixa Moldada 630A',
    category: 'MAIN_BREAKER',
    x: 100,
    y: 310,
    width: 140,
    height: 80,
    voltage: 380,
    nominalCurrent: 630,
    operationalCurrent: 480,
    poles: 3,
    breakingCapacity: 50,
    isEnergized: true,
    ports: [
      { id: 'p_q01_in', type: 'in', x: 170, y: 310 },
      { id: 'p_q01_out', type: 'out', x: 170, y: 390 }
    ],
    manufacturer: 'WEG',
    partNumber: 'DWA800H-630-3',
    unitCostBrl: 6450,
    statusText: 'Icu=50kA @ 380V (NBR IEC 60947-2)',
  },
  {
    id: 'comp_barramento',
    tag: 'BARRAMENTO_PRINCIPAL',
    name: 'Barramento de Cobre Eletrolítico 800A',
    category: 'BUSBAR',
    x: 50,
    y: 440,
    width: 720,
    height: 24,
    voltage: 380,
    nominalCurrent: 800,
    breakingCapacity: 35,
    isEnergized: true,
    ports: [
      { id: 'p_bar_main_in', type: 'in', x: 170, y: 440 },
      { id: 'p_bar_out_1', type: 'bus', x: 170, y: 464 },
      { id: 'p_bar_out_2', type: 'bus', x: 380, y: 464 },
      { id: 'p_bar_out_3', type: 'bus', x: 590, y: 464 },
    ],
    manufacturer: 'Termocobre',
    partNumber: 'Barra Cu 50x5mm',
    unitCostBrl: 4800,
    statusText: 'Barramento 3F+PE NBR 5410',
  },
  // Circuito 01 - Compressor Parafuso 30cv
  {
    id: 'comp_q02',
    tag: 'Q02_COMPRESSOR',
    name: 'Disjuntor Caixa Moldada 63A',
    category: 'MOTOR_BREAKER',
    x: 100,
    y: 510,
    width: 140,
    height: 70,
    voltage: 380,
    nominalCurrent: 63,
    operationalCurrent: 41.6,
    breakingCapacity: 25,
    isEnergized: true,
    cableCrossSection: 16,
    cableLength: 35,
    cableType: 'Afumex 90°C',
    voltageDropPercent: 1.15,
    ports: [
      { id: 'p_q02_in', type: 'in', x: 170, y: 510 },
      { id: 'p_q02_out', type: 'out', x: 170, y: 580 }
    ],
    manufacturer: 'WEG',
    partNumber: 'DWA160-63-3',
    unitCostBrl: 890,
    statusText: 'Circuito 01: Ib=41.6A, In=63A',
  },
  {
    id: 'comp_km01',
    tag: 'KM01_COMPRESSOR',
    name: 'Contator Tripolar 50A (AC-3)',
    category: 'CONTACTOR',
    x: 100,
    y: 610,
    width: 140,
    height: 65,
    voltage: 380,
    nominalCurrent: 50,
    operationalCurrent: 41.6,
    isEnergized: true,
    ports: [
      { id: 'p_km01_in', type: 'in', x: 170, y: 610 },
      { id: 'p_km01_out', type: 'out', x: 170, y: 675 }
    ],
    manufacturer: 'WEG',
    partNumber: 'CWB50-11-30D23',
    unitCostBrl: 420,
    statusText: 'Bobina 24VDC - AC-3 50A',
  },
  {
    id: 'comp_ft01',
    tag: 'FT01_TERMIC_COMP',
    name: 'Relé Térmico Sobrecarga 32-50A',
    category: 'THERMAL_RELAY',
    x: 100,
    y: 700,
    width: 140,
    height: 60,
    voltage: 380,
    nominalCurrent: 50,
    operationalCurrent: 41.6,
    isEnergized: true,
    ports: [
      { id: 'p_ft01_in', type: 'in', x: 170, y: 700 },
      { id: 'p_ft01_out', type: 'out', x: 170, y: 760 }
    ],
    manufacturer: 'WEG',
    partNumber: 'RW67-2D3-U050',
    unitCostBrl: 310,
    statusText: 'Ajuste: 42A (Classe 10)',
  },
  {
    id: 'comp_mtr01',
    tag: 'MTR01_COMPRESSOR',
    name: 'Motor Trifásico W22 Plus 30 CV',
    category: 'MOTOR_3P',
    x: 100,
    y: 790,
    width: 140,
    height: 80,
    voltage: 380,
    power: 22,
    powerHp: 30,
    nominalCurrent: 42,
    operationalCurrent: 41.6,
    powerFactor: 0.86,
    efficiency: 0.936,
    isEnergized: true,
    cableCrossSection: 16,
    ports: [
      { id: 'p_mtr01_in', type: 'in', x: 170, y: 790 }
    ],
    manufacturer: 'WEG',
    partNumber: 'W22 Premium 180M 4P',
    unitCostBrl: 9600,
    statusText: '30 CV (22kW) - 1770 RPM IE3',
  },
  // Circuito 02 - Exaustor Filtro Manga 10cv
  {
    id: 'comp_q03',
    tag: 'Q03_EXAUSTOR',
    name: 'Disjuntor-Motor MPW40 25A',
    category: 'MOTOR_BREAKER',
    x: 310,
    y: 510,
    width: 140,
    height: 70,
    voltage: 380,
    nominalCurrent: 25,
    operationalCurrent: 14.8,
    isEnergized: true,
    cableCrossSection: 6,
    cableLength: 20,
    voltageDropPercent: 0.72,
    ports: [
      { id: 'p_q03_in', type: 'in', x: 380, y: 510 },
      { id: 'p_q03_out', type: 'out', x: 380, y: 580 }
    ],
    manufacturer: 'WEG',
    partNumber: 'MPW40-3-U025',
    unitCostBrl: 380,
    statusText: 'Circuito 02: Ib=14.8A, In=25A',
  },
  {
    id: 'comp_vfd01',
    tag: 'VFD01_EXAUSTOR',
    name: 'Inversor de Frequência CFW500',
    category: 'VFD',
    x: 310,
    y: 610,
    width: 140,
    height: 80,
    voltage: 380,
    nominalCurrent: 16,
    power: 7.5,
    isEnergized: true,
    ports: [
      { id: 'p_vfd01_in', type: 'in', x: 380, y: 610 },
      { id: 'p_vfd01_out', type: 'out', x: 380, y: 690 }
    ],
    manufacturer: 'WEG',
    partNumber: 'CFW500B16P0T4',
    unitCostBrl: 3200,
    statusText: 'Modbus RTU / 60.0 Hz',
  },
  {
    id: 'comp_mtr02',
    tag: 'MTR02_EXAUSTOR',
    name: 'Motor Exaustão W22 10 CV',
    category: 'MOTOR_3P',
    x: 310,
    y: 720,
    width: 140,
    height: 80,
    voltage: 380,
    power: 7.5,
    powerHp: 10,
    nominalCurrent: 15.2,
    isEnergized: true,
    cableCrossSection: 6,
    ports: [
      { id: 'p_mtr02_in', type: 'in', x: 380, y: 720 }
    ],
    manufacturer: 'WEG',
    partNumber: 'W22 132S 4P',
    unitCostBrl: 3850,
    statusText: '10 CV (7.5kW) - 1750 RPM',
  },
  // Circuito 03 - Banco de Capacitores e Proteção Geral DPS + DR
  {
    id: 'comp_dps_dr',
    tag: 'PROT_DPS_DR',
    name: 'Conjunto DPS Classe II + DR 300mA',
    category: 'DPS_PROTECTION',
    x: 520,
    y: 510,
    width: 140,
    height: 70,
    voltage: 380,
    nominalCurrent: 63,
    isEnergized: true,
    ports: [
      { id: 'p_dps_in', type: 'in', x: 590, y: 510 },
      { id: 'p_dps_out', type: 'out', x: 590, y: 580 }
    ],
    manufacturer: 'Schneider Electric',
    partNumber: 'Acti9 iPRD40r + iID 4P 300mA',
    unitCostBrl: 1850,
    statusText: 'NBR 5410 Proteção contra surtos',
  },
  {
    id: 'comp_cap_bank',
    tag: 'BANCO_CAP_30KVAR',
    name: 'Banco Automático de Capacitores 30 kVAr',
    category: 'CAPACITOR_BANK',
    x: 520,
    y: 610,
    width: 140,
    height: 75,
    voltage: 380,
    nominalCurrent: 45.6,
    operationalCurrent: 45.6,
    power: 30, // kvar
    isEnergized: true,
    ports: [
      { id: 'p_cap_in', type: 'in', x: 590, y: 610 }
    ],
    manufacturer: 'WEG',
    partNumber: 'BCW 30kvar 380V 60Hz',
    unitCostBrl: 4200,
    statusText: 'Correção cos φ >= 0.95',
  },
];

export const INITIAL_CONNECTIONS: ElectricalConnection[] = [
  { id: 'conn_1', fromComponentId: 'comp_sub_mt', fromPortId: 'p_sub_out', toComponentId: 'comp_trafo_01', toPortId: 'p_tr_in', isEnergized: true, voltage: 13800, wireGauge: 35 },
  { id: 'conn_2', fromComponentId: 'comp_trafo_01', fromPortId: 'p_tr_out', toComponentId: 'comp_q01', toPortId: 'p_q01_in', isEnergized: true, voltage: 380, wireGauge: 240 },
  { id: 'conn_3', fromComponentId: 'comp_q01', fromPortId: 'p_q01_out', toComponentId: 'comp_barramento', toPortId: 'p_bar_main_in', isEnergized: true, voltage: 380, wireGauge: 240 },
  // Circuito 01
  { id: 'conn_cct1_a', fromComponentId: 'comp_barramento', fromPortId: 'p_bar_out_1', toComponentId: 'comp_q02', toPortId: 'p_q02_in', isEnergized: true, voltage: 380, wireGauge: 16 },
  { id: 'conn_cct1_b', fromComponentId: 'comp_q02', fromPortId: 'p_q02_out', toComponentId: 'comp_km01', toPortId: 'p_km01_in', isEnergized: true, voltage: 380, wireGauge: 16 },
  { id: 'conn_cct1_c', fromComponentId: 'comp_km01', fromPortId: 'p_km01_out', toComponentId: 'comp_ft01', toPortId: 'p_ft01_in', isEnergized: true, voltage: 380, wireGauge: 16 },
  { id: 'conn_cct1_d', fromComponentId: 'comp_ft01', fromPortId: 'p_ft01_out', toComponentId: 'comp_mtr01', toPortId: 'p_mtr01_in', isEnergized: true, voltage: 380, wireGauge: 16 },
  // Circuito 02
  { id: 'conn_cct2_a', fromComponentId: 'comp_barramento', fromPortId: 'p_bar_out_2', toComponentId: 'comp_q03', toPortId: 'p_q03_in', isEnergized: true, voltage: 380, wireGauge: 6 },
  { id: 'conn_cct2_b', fromComponentId: 'comp_q03', fromPortId: 'p_q03_out', toComponentId: 'comp_vfd01', toPortId: 'p_vfd01_in', isEnergized: true, voltage: 380, wireGauge: 6 },
  { id: 'conn_cct2_c', fromComponentId: 'comp_vfd01', fromPortId: 'p_vfd01_out', toComponentId: 'comp_mtr02', toPortId: 'p_mtr02_in', isEnergized: true, voltage: 380, wireGauge: 6 },
  // Circuito 03
  { id: 'conn_cct3_a', fromComponentId: 'comp_barramento', fromPortId: 'p_bar_out_3', toComponentId: 'comp_dps_dr', toPortId: 'p_dps_in', isEnergized: true, voltage: 380, wireGauge: 10 },
  { id: 'conn_cct3_b', fromComponentId: 'comp_dps_dr', fromPortId: 'p_dps_out', toComponentId: 'comp_cap_bank', toPortId: 'p_cap_in', isEnergized: true, voltage: 380, wireGauge: 10 },
];

// INITIAL LADDER LOGIC (IEC 61131-3)
export const INITIAL_LADDER_RUNGS: LadderRung[] = [
  {
    id: 'rung_0',
    number: 0,
    title: 'Linha de Segurança Geral & Emergência NR-10/NR-12',
    comment: 'Condição segura: Botão de emergência acionado (NF) e relé térmico compressor normal (NF).',
    isPowerFlowActive: true,
    elements: [
      { id: 'e0_1', type: 'CONTACT_NO', tagId: 'tag_btn_emerg', tagName: 'BTN_EMERGENCIA', address: '%I0.0', isEnergized: true, colIndex: 0 },
      { id: 'e0_2', type: 'CONTACT_NO', tagId: 'tag_ft01_trip', tagName: 'FT01_TERMIC_COMP', address: '%I0.1', isEnergized: true, colIndex: 1 },
      { id: 'e0_3', type: 'COIL', tagId: 'tag_q01_geral', tagName: 'Q01_GERAL', address: '%Q0.0', isEnergized: true, colIndex: 4 },
    ],
  },
  {
    id: 'rung_1',
    number: 1,
    title: 'Comando de Partida com Selo (Start/Stop) Compressor KM01',
    comment: 'Lógica padrão industrial de auto-retenção do contator KM01.',
    isPowerFlowActive: true,
    elements: [
      { id: 'e1_1', type: 'CONTACT_NO', tagId: 'tag_km01_comp', tagName: 'KM01_COMPRESSOR', address: '%Q0.2', isEnergized: true, colIndex: 0 },
      { id: 'e1_2', type: 'CONTACT_NO', tagId: 'tag_btn_parada', tagName: 'BTN_PARADA_COMP', address: '%I0.3', isEnergized: true, colIndex: 1 },
      { id: 'e1_3', type: 'COIL', tagId: 'tag_km01_comp', tagName: 'KM01_COMPRESSOR', address: '%Q0.2', isEnergized: true, colIndex: 4 },
    ],
  },
  {
    id: 'rung_2',
    number: 2,
    title: 'Temporizador de Transição Estrela-Triângulo IEC TON',
    comment: 'Transição após 6 segundos para aliviar corrente de partida per NBR 5410.',
    isPowerFlowActive: true,
    elements: [
      { id: 'e2_1', type: 'CONTACT_NO', tagId: 'tag_km01_comp', tagName: 'KM01_COMPRESSOR', address: '%Q0.2', isEnergized: true, colIndex: 0 },
      { id: 'e2_2', type: 'TIMER_TON', tagId: 'tag_tmr_yd', tagName: 'TMR_STAR_DELTA', address: '%T01', presetTime: 'T#6s', elapsedTime: 'T#6s', isEnergized: true, colIndex: 2 },
      { id: 'e2_3', type: 'COIL', tagId: 'tag_km03_triang', tagName: 'KM03_TRIANGULO', address: '%Q0.4', isEnergized: true, colIndex: 4 },
    ],
  },
  {
    id: 'rung_3',
    number: 3,
    title: 'Sinalização de Falha e Trip Sobrecarga Térmica',
    comment: 'Quando o relé térmico abre (desenergizado), aciona a lâmpada de falha.',
    isPowerFlowActive: false,
    elements: [
      { id: 'e3_1', type: 'CONTACT_NC', tagId: 'tag_ft01_trip', tagName: 'FT01_TERMIC_COMP', address: '%I0.1', isEnergized: false, colIndex: 0 },
      { id: 'e3_2', type: 'COIL', tagId: 'tag_lamp_alarme', tagName: 'LAMP_ALARME_FALHA', address: '%Q0.7', isEnergized: false, colIndex: 4 },
    ],
  },
];

// INITIAL FBD (FUNCTION BLOCK DIAGRAM)
export const INITIAL_FBD_BLOCKS: FbdBlock[] = [
  {
    id: 'fbd_blk_safety',
    type: 'AND',
    title: 'INTERTRAVAMENTO_SEGURANCA',
    x: 60,
    y: 60,
    inputs: [
      { id: 'in_emerg', name: 'EMERG_OK', type: 'BOOL', direction: 'in', value: true },
      { id: 'in_thermal', name: 'THERMAL_OK', type: 'BOOL', direction: 'in', value: true },
      { id: 'in_pres_sw', name: 'PRESS_OK', type: 'BOOL', direction: 'in', value: true },
    ],
    outputs: [
      { id: 'out_safety_ready', name: 'SYSTEM_READY', type: 'BOOL', direction: 'out', value: true },
    ],
  },
  {
    id: 'fbd_blk_starter',
    type: 'MOTOR_STARTER_BLOCK',
    title: 'WEG_DOL_CONTROLLER',
    x: 320,
    y: 60,
    inputs: [
      { id: 'in_start', name: 'START_CMD', type: 'BOOL', direction: 'in', value: true },
      { id: 'in_stop', name: 'STOP_CMD', type: 'BOOL', direction: 'in', value: false },
      { id: 'in_interlock', name: 'INTERLOCK', type: 'BOOL', direction: 'in', value: true },
    ],
    outputs: [
      { id: 'out_km1', name: 'KM01_COIL', type: 'BOOL', direction: 'out', value: true },
      { id: 'out_running', name: 'RUN_FEEDBACK', type: 'BOOL', direction: 'out', value: true },
      { id: 'out_fault', name: 'TRIP_ALARM', type: 'BOOL', direction: 'out', value: false },
    ],
  },
  {
    id: 'fbd_blk_scale',
    type: 'SCALE_AI',
    title: 'TRANSMITTER_SCALING',
    x: 320,
    y: 280,
    parameters: {
      RAW_MIN: 0,
      RAW_MAX: 27648,
      ENG_MIN: 0.0,
      ENG_MAX: 16.0,
      UNIT: 'bar',
    },
    inputs: [
      { id: 'in_raw_ai', name: 'RAW_IN (%IW66)', type: 'INT', direction: 'in', value: 12800 },
    ],
    outputs: [
      { id: 'out_eng_val', name: 'ENG_VAL (bar)', type: 'REAL', direction: 'out', value: 7.42 },
    ],
  },
];

export const INITIAL_FBD_WIRES: FbdWire[] = [
  {
    id: 'fbd_w1',
    fromBlockId: 'fbd_blk_safety',
    fromPinId: 'out_safety_ready',
    toBlockId: 'fbd_blk_starter',
    toPinId: 'in_interlock',
    isActive: true,
  },
];

// INITIAL PLC RACK (8-SLOT MODULAR CHASSIS)
export const INITIAL_PLC_RACK: PlcRackConfig = {
  chassisName: 'RACK_01_CCM_AUTOMATION',
  model: 'EletricAI S7-Edge',
  ipAddress: '192.168.10.20',
  subnetMask: '255.255.255.0',
  cycleTimeMs: 12,
  slots: [
    {
      slotNumber: 0,
      moduleType: 'POWER_SUPPLY',
      name: 'Fonte Chaveada PS 24VDC 10A',
      partNumber: 'PS-307-10A',
      startAddress: '-',
      endAddress: '-',
      channelCount: 1,
      status: 'OK',
      mappedTags: [],
    },
    {
      slotNumber: 1,
      moduleType: 'CPU',
      name: 'CPU 1515F-2 PN Fail-Safe SIL3',
      partNumber: '6ES7-515-2FM01-0AB0',
      startAddress: '%M0.0',
      endAddress: '%M255.7',
      channelCount: 1,
      status: 'OK',
      mappedTags: ['TMR_STAR_DELTA'],
    },
    {
      slotNumber: 2,
      moduleType: 'DI_16',
      name: 'Entradas Digitais 16x24VDC',
      partNumber: 'DI 16x24VDC HF',
      startAddress: '%I0.0',
      endAddress: '%I1.7',
      channelCount: 16,
      status: 'OK',
      mappedTags: ['BTN_EMERGENCIA', 'FT01_TERMIC_COMP', 'BTN_PARTIDA_COMP', 'BTN_PARADA_COMP'],
    },
    {
      slotNumber: 3,
      moduleType: 'DO_16',
      name: 'Saídas Digitais 16x24VDC 0.5A Transistor',
      partNumber: 'DQ 16x24VDC 0.5A HF',
      startAddress: '%Q0.0',
      endAddress: '%Q1.7',
      channelCount: 16,
      status: 'OK',
      mappedTags: ['Q01_GERAL', 'Q02_COMPRESSOR', 'KM01_COMPRESSOR', 'KM02_ESTRELA', 'KM03_TRIANGULO', 'Q03_EXAUSTOR', 'KM04_EXAUSTOR', 'LAMP_ALARME_FALHA'],
    },
    {
      slotNumber: 4,
      moduleType: 'AI_8',
      name: 'Entradas Analógicas 8xU/I 16bit',
      partNumber: 'AI 8xU/I/RTD/TC 16bit',
      startAddress: '%IW64',
      endAddress: '%IW78',
      channelCount: 8,
      status: 'OK',
      mappedTags: ['TEMP_MANCAL_COMP', 'PRESSAO_REDE_AR', 'CORRENTE_FASE_R'],
    },
    {
      slotNumber: 5,
      moduleType: 'AO_4',
      name: 'Saídas Analógicas 4xU/I 16bit',
      partNumber: 'AQ 4xU/I 16bit',
      startAddress: '%QW64',
      endAddress: '%QW70',
      channelCount: 4,
      status: 'OK',
      mappedTags: [],
    },
    {
      slotNumber: 6,
      moduleType: 'COMM_MODBUS',
      name: 'Módulo Comunicação Modbus TCP / RTU',
      partNumber: 'CM PtP RS485/422',
      startAddress: 'MB_NODE_01',
      endAddress: 'MB_NODE_16',
      channelCount: 2,
      status: 'OK',
      mappedTags: ['VFD01_EXAUSTOR'],
    },
  ],
};

// INITIAL SCADA WIDGETS
export const INITIAL_SCADA_WIDGETS: ScadaWidget[] = [
  { id: 'w_mtr1', type: 'MOTOR_INDICATOR', tagId: 'tag_km01_comp', tagName: 'KM01_COMPRESSOR', title: 'Compressor Parafuso 30cv', x: 40, y: 40, width: 220, height: 160 },
  { id: 'w_press', type: 'ANALOG_GAUGE', tagId: 'tag_press_ar', tagName: 'PRESSAO_REDE_AR', title: 'Pressão Reservatório', x: 280, y: 40, width: 200, height: 160, min: 0, max: 16, unit: 'bar' },
  { id: 'w_temp', type: 'BAR_GRAPH', tagId: 'tag_temp_mancl', tagName: 'TEMP_MANCAL_COMP', title: 'Temp. Mancal MTR01', x: 500, y: 40, width: 180, height: 160, min: 0, max: 120, unit: '°C' },
  { id: 'w_curr', type: 'ANALOG_GAUGE', tagId: 'tag_corrente_r', tagName: 'CORRENTE_FASE_R', title: 'Corrente Fase R (A)', x: 700, y: 40, width: 200, height: 160, min: 0, max: 80, unit: 'A' },
  { id: 'w_mtr2', type: 'MOTOR_INDICATOR', tagId: 'tag_km04_exaustor', tagName: 'KM04_EXAUSTOR', title: 'Exaustor Filtro Manga 10cv', x: 40, y: 220, width: 220, height: 160 },
  { id: 'w_chart', type: 'TREND_CHART', tagId: 'tag_press_ar', tagName: 'PRESSAO_REDE_AR', title: 'Tendência de Pressão & Corrente', x: 280, y: 220, width: 620, height: 210 },
];

// INITIAL SCADA SCRIPT (Web Worker Sandbox)
export const INITIAL_SCADA_SANDBOX_SCRIPT = `// SCADA Sandbox Script - EletricAI Air-Gapped Web Worker
// Executado em loop cíclico sem acesso a DOM ou rede.
// tags: objeto com valores atuais das tags.

function executeCycle(tags) {
  const logs = [];
  
  // 1. Verificação de Alarme de Temperatura de Mancal
  if (tags.TEMP_MANCAL_COMP > 80.0) {
    logs.push({ level: 'WARN', message: 'Temperatura de mancal elevada: ' + tags.TEMP_MANCAL_COMP.toFixed(1) + '°C (Limite NBR: 85°C)' });
  }

  // 2. Intertravamento de Segurança de Pressão Máxima
  if (tags.PRESSAO_REDE_AR >= 9.2) {
    logs.push({ level: 'INFO', message: 'Pressão nominal atingida (9.2 bar). Aliviando carga do compressor.' });
  }

  // 3. Monitoramento de Assimetria de Corrente
  const iR = tags.CORRENTE_FASE_R || 41.6;
  if (iR > 50.0) {
    logs.push({ level: 'WARN', message: 'Alerta de sobrecorrente Fase R: ' + iR.toFixed(1) + 'A (In=42A)' });
  }

  return {
    status: 'CYCLE_COMPLETED',
    timestamp: new Date().toLocaleTimeString(),
    logs: logs
  };
}
`;

// INITIAL DIGITAL TWIN 3D HOTSPOTS
export const INITIAL_TWIN_HOTSPOTS: DigitalTwinHotspot[] = [
  {
    id: 'twin_cubicle_in',
    tag: 'Q01_GERAL',
    name: 'Gaveta Entrada Geral Q01 (630A)',
    componentType: 'CUBICLE_INCOMING',
    position3D: [-2.2, 1.2, 0],
    telemetry: {
      tagId: 'tag_q01_geral',
      voltageL1L2: 382.4,
      voltageL2L3: 381.1,
      voltageL3L1: 382.8,
      currentL1: 64.2,
      currentL2: 63.8,
      currentL3: 64.9,
      frequencyHz: 60.01,
      powerFactor: 0.94,
      activePowerKw: 38.6,
      temperatureCelsius: 38.2,
      breakerClosed: true,
      alarmTrip: false,
    },
    warningStatus: 'NORMAL',
  },
  {
    id: 'twin_cubicle_q02',
    tag: 'Q02_COMPRESSOR',
    name: 'Gaveta CCM Q02 - Compressor 30cv',
    componentType: 'CUBICLE_FEEDER',
    position3D: [-0.7, 1.4, 0],
    telemetry: {
      tagId: 'tag_q02_comp',
      voltageL1L2: 380.2,
      voltageL2L3: 379.8,
      voltageL3L1: 380.5,
      currentL1: 41.6,
      currentL2: 41.2,
      currentL3: 41.8,
      frequencyHz: 60.0,
      powerFactor: 0.86,
      activePowerKw: 22.4,
      temperatureCelsius: 44.5,
      breakerClosed: true,
      alarmTrip: false,
    },
    warningStatus: 'NORMAL',
  },
  {
    id: 'twin_motor_drive',
    tag: 'MTR01_COMPRESSOR',
    name: 'Motor W22 Premium 30 CV - Planta Moagem',
    componentType: 'MOTOR_DRIVE',
    position3D: [1.8, 0.6, 0.4],
    telemetry: {
      tagId: 'tag_km01_comp',
      voltageL1L2: 378.5,
      voltageL2L3: 377.9,
      voltageL3L1: 378.8,
      currentL1: 41.6,
      currentL2: 41.2,
      currentL3: 41.8,
      frequencyHz: 60.0,
      powerFactor: 0.86,
      activePowerKw: 22.0,
      temperatureCelsius: 64.8,
      vibrationMmS: 1.8,
      breakerClosed: true,
      alarmTrip: false,
    },
    warningStatus: 'NORMAL',
  },
  {
    id: 'twin_trafo',
    tag: 'TR01_1000KVA',
    name: 'Subestação Abrigada Trafo 1000 kVA',
    componentType: 'TRANSFORMER',
    position3D: [-4.0, 1.6, -1.0],
    telemetry: {
      tagId: 'tag_q01_geral',
      voltageL1L2: 13800,
      voltageL2L3: 13800,
      voltageL3L1: 13800,
      currentL1: 41.8,
      currentL2: 41.6,
      currentL3: 41.9,
      frequencyHz: 60.0,
      powerFactor: 0.93,
      activePowerKw: 850,
      temperatureCelsius: 58.3,
      breakerClosed: true,
      alarmTrip: false,
    },
    warningStatus: 'NORMAL',
  },
];

// INITIAL BILL OF MATERIALS (BOM) & MEMORIAL DESCRITIVO
export const INITIAL_BOM_ITEMS: BomItem[] = [
  {
    id: 'bom_1',
    itemNumber: 1,
    tag: 'Q01_GERAL',
    description: 'Disjuntor Caixa Moldada 630A Tripolar Icu=50kA @ 380V',
    category: 'Disjuntores Caixa Moldada',
    normReference: 'NBR IEC 60947-2 / NBR 5410',
    manufacturer: 'WEG',
    model: 'DWA800H-630-3',
    quantity: 1,
    unit: 'pç',
    unitPriceBrl: 6450.0,
    totalPriceBrl: 6450.0,
    deliveryTimeDays: 7,
  },
  {
    id: 'bom_2',
    itemNumber: 2,
    tag: 'Q02_COMPRESSOR',
    description: 'Disjuntor Caixa Moldada 63A Tripolar Icu=25kA',
    category: 'Disjuntores Caixa Moldada',
    normReference: 'NBR 5410 item 5.3.4 (Sobrecarga)',
    manufacturer: 'WEG',
    model: 'DWA160-63-3',
    quantity: 1,
    unit: 'pç',
    unitPriceBrl: 890.0,
    totalPriceBrl: 890.0,
    deliveryTimeDays: 3,
  },
  {
    id: 'bom_3',
    itemNumber: 3,
    tag: 'KM01_COMPRESSOR',
    description: 'Contator de Potência 50A AC-3 24VDC',
    category: 'Contatores',
    normReference: 'NBR IEC 60947-4-1',
    manufacturer: 'WEG',
    model: 'CWB50-11-30D23',
    quantity: 1,
    unit: 'pç',
    unitPriceBrl: 420.0,
    totalPriceBrl: 420.0,
    deliveryTimeDays: 3,
  },
  {
    id: 'bom_4',
    itemNumber: 4,
    tag: 'FT01_TERMIC_COMP',
    description: 'Relé Térmico Bimetálico Sobrecarga 32-50A Classe 10',
    category: 'Proteção Térmica',
    normReference: 'NBR 5410 item 5.3.4.1',
    manufacturer: 'WEG',
    model: 'RW67-2D3-U050',
    quantity: 1,
    unit: 'pç',
    unitPriceBrl: 310.0,
    totalPriceBrl: 310.0,
    deliveryTimeDays: 3,
  },
  {
    id: 'bom_5',
    itemNumber: 5,
    tag: 'CABO_CCT1',
    description: 'Cabo de Cobre Sintenax Afumex 0,6/1kV 90°C 16 mm² (L1,L2,L3,PE)',
    category: 'Cabos e Condutores',
    normReference: 'NBR 5410 Tabela 36 / 38 / 40',
    manufacturer: 'Prysmian',
    model: 'Afumex Plus 1kV 16mm²',
    quantity: 140, // 4 condutores x 35 metros
    unit: 'metros',
    unitPriceBrl: 18.50,
    totalPriceBrl: 2590.0,
    deliveryTimeDays: 5,
  },
  {
    id: 'bom_6',
    itemNumber: 6,
    tag: 'VFD01_EXAUSTOR',
    description: 'Inversor de Frequência 10 CV (7.5 kW) 380V Trifásico',
    category: 'Acionamentos',
    normReference: 'IEC 61800-3',
    manufacturer: 'WEG',
    model: 'CFW500B16P0T4',
    quantity: 1,
    unit: 'pç',
    unitPriceBrl: 3200.0,
    totalPriceBrl: 3200.0,
    deliveryTimeDays: 4,
  },
  {
    id: 'bom_7',
    itemNumber: 7,
    tag: 'PROT_DPS_DR',
    description: 'Dispositivo DPS Classe II 45kA + Dispositivo DR 300mA Seletivo',
    category: 'Proteção Diferencial e Surtos',
    normReference: 'NBR 5410 item 5.4.3 / item 6.3.5',
    manufacturer: 'Schneider Electric',
    model: 'iPRD40r + Acti9 iID 4P',
    quantity: 1,
    unit: 'cj',
    unitPriceBrl: 1850.0,
    totalPriceBrl: 1850.0,
    deliveryTimeDays: 5,
  },
  {
    id: 'bom_8',
    itemNumber: 8,
    tag: 'BARRA_CU_800A',
    description: 'Barramento Cobre Eletrolítico 50x5mm Pintado NBR 5410',
    category: 'Barramentos e Acessórios',
    normReference: 'NBR 5410 / NBR IEC 61439-1',
    manufacturer: 'Termocobre',
    model: 'Cu Eletrolítico 99.9%',
    quantity: 12,
    unit: 'kg',
    unitPriceBrl: 110.0,
    totalPriceBrl: 1320.0,
    deliveryTimeDays: 2,
  },
];
