import { ComponentCategory } from '@/types/electrical';

export interface SymbolDefinition {
  id: string;
  category: 
    | 'FONTES'
    | 'PROTECAO'
    | 'COMANDO'
    | 'CARGAS'
    | 'MEDICAO'
    | 'INSTRUMENTACAO'
    | 'CONEXAO'
    | 'ATERRAMENTO'
    | 'COMUNICACAO';
  name: string;
  shortDescription: string;
  iecCode: string;
  tagPrefix: string;
  defaultCategory: ComponentCategory;
  width: number;
  height: number;
  defaultNominalCurrent?: number;
  defaultVoltage?: number;
  defaultPowerKw?: number;
  defaultManufacturer?: string;
  defaultPartNumber?: string;
  iconType: string;
  ports: Array<{ id: string; type: 'in' | 'out' | 'bus'; x: number; y: number; label: string }>;
}

export const SYMBOL_LIBRARY: SymbolDefinition[] = [
  // FONTES
  {
    id: 'sym_rede_concessionaria',
    category: 'FONTES',
    name: 'Rede Concessionária MT',
    shortDescription: 'Ponto de Conexão à Concessionária 13.8kV',
    iecCode: 'IEC 60617-02-01',
    tagPrefix: 'ENTRADA',
    defaultCategory: 'SOURCE_MT',
    width: 140,
    height: 70,
    defaultVoltage: 13800,
    defaultNominalCurrent: 200,
    defaultManufacturer: 'Concessionária Local',
    iconType: 'grid',
    ports: [{ id: 'p_out', type: 'out', x: 70, y: 70, label: 'Saída MT' }],
  },
  {
    id: 'sym_transformador_mt_bt',
    category: 'FONTES',
    name: 'Transformador MT/BT',
    shortDescription: 'Trafo a Óleo/Seco 13.8kV -> 380/220V',
    iecCode: 'IEC 60617-06-09',
    tagPrefix: 'TR',
    defaultCategory: 'TRANSFORMER_MT_BT',
    width: 140,
    height: 90,
    defaultVoltage: 380,
    defaultNominalCurrent: 1519,
    defaultPowerKw: 1000,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'Trafo 1000kVA',
    iconType: 'transformer',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'Primário MT' },
      { id: 'p_out', type: 'out', x: 70, y: 90, label: 'Secundário BT' },
    ],
  },
  {
    id: 'sym_gerador_emergencia',
    category: 'FONTES',
    name: 'Grupo Moto-Gerador',
    shortDescription: 'Gerador Diesel de Emergência com ATS',
    iecCode: 'IEC 60617-06-01',
    tagPrefix: 'GMG',
    defaultCategory: 'SOURCE_MT',
    width: 140,
    height: 80,
    defaultVoltage: 380,
    defaultNominalCurrent: 500,
    defaultPowerKw: 350,
    defaultManufacturer: 'Stemac',
    defaultPartNumber: 'GMG-350kVA',
    iconType: 'generator',
    ports: [{ id: 'p_out', type: 'out', x: 70, y: 80, label: 'G_OUT' }],
  },
  {
    id: 'sym_ups_nobreak',
    category: 'FONTES',
    name: 'UPS / Nobreak Industrial',
    shortDescription: 'Sistema Online Dupla Conversão 220V',
    iecCode: 'IEC 60617-06-13',
    tagPrefix: 'UPS',
    defaultCategory: 'DISTRIBUTION_BOARD',
    width: 140,
    height: 75,
    defaultVoltage: 220,
    defaultNominalCurrent: 63,
    defaultPowerKw: 15,
    defaultManufacturer: 'Schneider',
    defaultPartNumber: 'Galaxy 300',
    iconType: 'ups',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'Rede AC' },
      { id: 'p_out', type: 'out', x: 70, y: 75, label: 'Carga Crítica' },
    ],
  },
  {
    id: 'sym_barramento_cu',
    category: 'FONTES',
    name: 'Barramento de Cobre',
    shortDescription: 'Barramento Principal 3F+N+PE',
    iecCode: 'IEC 60617-03-01',
    tagPrefix: 'BAR',
    defaultCategory: 'BUSBAR',
    width: 720,
    height: 24,
    defaultVoltage: 380,
    defaultNominalCurrent: 800,
    defaultManufacturer: 'Termocobre',
    defaultPartNumber: 'Cu 50x5mm',
    iconType: 'busbar',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'Alimentação' },
      { id: 'p_out_1', type: 'bus', x: 170, y: 24, label: 'Saída 1' },
      { id: 'p_out_2', type: 'bus', x: 380, y: 24, label: 'Saída 2' },
      { id: 'p_out_3', type: 'bus', x: 590, y: 24, label: 'Saída 3' },
    ],
  },

  // PROTEÇÃO
  {
    id: 'sym_disjuntor_caixa_moldada',
    category: 'PROTECAO',
    name: 'Disjuntor Caixa Moldada',
    shortDescription: 'Disjuntor Tripolar Icu 50kA NBR IEC 60947-2',
    iecCode: 'IEC 60617-07-13',
    tagPrefix: 'Q',
    defaultCategory: 'MAIN_BREAKER',
    width: 140,
    height: 75,
    defaultVoltage: 380,
    defaultNominalCurrent: 630,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'DWA800H',
    iconType: 'mccb',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'L1-L2-L3' },
      { id: 'p_out', type: 'out', x: 70, y: 75, label: 'T1-T2-T3' },
    ],
  },
  {
    id: 'sym_disjuntor_motor',
    category: 'PROTECAO',
    name: 'Disjuntor-Motor Magnético/Térmico',
    shortDescription: 'Proteção contra curto-circuito e sobrecarga MPW',
    iecCode: 'IEC 60617-07-14',
    tagPrefix: 'QM',
    defaultCategory: 'MOTOR_BREAKER',
    width: 140,
    height: 70,
    defaultVoltage: 380,
    defaultNominalCurrent: 32,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'MPW40-32',
    iconType: 'motor_breaker',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: '1-3-5' },
      { id: 'p_out', type: 'out', x: 70, y: 70, label: '2-4-6' },
    ],
  },
  {
    id: 'sym_rele_termico',
    category: 'PROTECAO',
    name: 'Relé Térmico de Sobrecarga',
    shortDescription: 'Bimetálico Classe 10 com contatos 95-96 e 97-98',
    iecCode: 'IEC 60617-07-15',
    tagPrefix: 'FT',
    defaultCategory: 'THERMAL_RELAY',
    width: 140,
    height: 60,
    defaultVoltage: 380,
    defaultNominalCurrent: 40,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'RW67',
    iconType: 'thermal_relay',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'Entrada' },
      { id: 'p_out', type: 'out', x: 70, y: 60, label: 'Saída' },
    ],
  },
  {
    id: 'sym_dr_diferencial',
    category: 'PROTECAO',
    name: 'Módulo DR (30mA / 300mA)',
    shortDescription: 'Interruptor Diferencial Residual NBR 5410',
    iecCode: 'IEC 60617-07-18',
    tagPrefix: 'DR',
    defaultCategory: 'DR_PROTECTION',
    width: 140,
    height: 65,
    defaultVoltage: 380,
    defaultNominalCurrent: 63,
    defaultManufacturer: 'Schneider',
    defaultPartNumber: 'Acti9 iID',
    iconType: 'rcd',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'Entrada' },
      { id: 'p_out', type: 'out', x: 70, y: 65, label: 'Saída' },
    ],
  },
  {
    id: 'sym_dps_surtos',
    category: 'PROTECAO',
    name: 'DPS Classe II (45kA)',
    shortDescription: 'Dispositivo Proteção Contra Surtos Atmosféricos',
    iecCode: 'IEC 60617-07-22',
    tagPrefix: 'DPS',
    defaultCategory: 'DPS_PROTECTION',
    width: 140,
    height: 65,
    defaultVoltage: 380,
    defaultNominalCurrent: 45,
    defaultManufacturer: 'Schneider',
    defaultPartNumber: 'iPRD40r',
    iconType: 'spd',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'Fase' },
      { id: 'p_out', type: 'out', x: 70, y: 65, label: 'Terra PE' },
    ],
  },

  // COMANDO
  {
    id: 'sym_contator_tripolar',
    category: 'COMANDO',
    name: 'Contator Tripolar AC-3',
    shortDescription: 'Chave eletromagnética de potência com bobina 24VDC',
    iecCode: 'IEC 60617-07-01',
    tagPrefix: 'KM',
    defaultCategory: 'CONTACTOR',
    width: 140,
    height: 65,
    defaultVoltage: 380,
    defaultNominalCurrent: 50,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'CWB50',
    iconType: 'contactor',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: '1-3-5' },
      { id: 'p_out', type: 'out', x: 70, y: 65, label: '2-4-6' },
    ],
  },
  {
    id: 'sym_soft_starter',
    category: 'COMANDO',
    name: 'Soft-Starter com Bypass',
    shortDescription: 'Partida suave por tiristores SSW07',
    iecCode: 'IEC 60617-07-25',
    tagPrefix: 'SS',
    defaultCategory: 'SOFT_STARTER',
    width: 140,
    height: 75,
    defaultVoltage: 380,
    defaultNominalCurrent: 45,
    defaultPowerKw: 22,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'SSW07-0045T',
    iconType: 'soft_starter',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'L1-L2-L3' },
      { id: 'p_out', type: 'out', x: 70, y: 75, label: 'U-V-W' },
    ],
  },
  {
    id: 'sym_inversor_vfd',
    category: 'COMANDO',
    name: 'Inversor de Frequência VFD',
    shortDescription: 'Acionamento de velocidade variável CFW500',
    iecCode: 'IEC 60617-07-26',
    tagPrefix: 'VFD',
    defaultCategory: 'VFD',
    width: 140,
    height: 80,
    defaultVoltage: 380,
    defaultNominalCurrent: 16,
    defaultPowerKw: 7.5,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'CFW500B16P0T4',
    iconType: 'vfd',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'R-S-T' },
      { id: 'p_out', type: 'out', x: 70, y: 80, label: 'U-V-W' },
    ],
  },

  // CARGAS
  {
    id: 'sym_motor_3f',
    category: 'CARGAS',
    name: 'Motor Trifásico Gaiola W22',
    shortDescription: 'Motor de Indução Alto Rendimento IE3 / NBR 17094',
    iecCode: 'IEC 60617-06-04',
    tagPrefix: 'M',
    defaultCategory: 'MOTOR_3P',
    width: 140,
    height: 80,
    defaultVoltage: 380,
    defaultNominalCurrent: 42,
    defaultPowerKw: 22,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'W22 180M 30CV',
    iconType: 'motor_3p',
    ports: [{ id: 'p_in', type: 'in', x: 70, y: 0, label: 'U-V-W' }],
  },
  {
    id: 'sym_banco_capacitores',
    category: 'CARGAS',
    name: 'Banco de Capacitores',
    shortDescription: 'Correção de Fator de Potência cos φ >= 0.95',
    iecCode: 'IEC 60617-04-02',
    tagPrefix: 'BC',
    defaultCategory: 'CAPACITOR_BANK',
    width: 140,
    height: 70,
    defaultVoltage: 380,
    defaultNominalCurrent: 45.6,
    defaultPowerKw: 30,
    defaultManufacturer: 'WEG',
    defaultPartNumber: 'BCW 30kvar',
    iconType: 'capacitor',
    ports: [{ id: 'p_in', type: 'in', x: 70, y: 0, label: 'Alimentação' }],
  },
  {
    id: 'sym_bomba_hidraulica',
    category: 'CARGAS',
    name: 'Bomba Centrífuga Industrial',
    shortDescription: 'Conjunto Moto-Bomba de Pressurização',
    iecCode: 'IEC 60617-06-04',
    tagPrefix: 'BMB',
    defaultCategory: 'MOTOR_3P',
    width: 140,
    height: 80,
    defaultVoltage: 380,
    defaultNominalCurrent: 28,
    defaultPowerKw: 15,
    defaultManufacturer: 'KSB',
    defaultPartNumber: 'Megabloc 15kW',
    iconType: 'pump',
    ports: [{ id: 'p_in', type: 'in', x: 70, y: 0, label: 'U-V-W' }],
  },

  // MEDIÇÃO & INSTRUMENTAÇÃO
  {
    id: 'sym_multimedidor',
    category: 'MEDICAO',
    name: 'Multimedidor Grandezas Elétricas',
    shortDescription: 'Medição V, I, kW, kVA, THD, cos φ via Modbus RTU',
    iecCode: 'IEC 60617-08-01',
    tagPrefix: 'ME',
    defaultCategory: 'DISTRIBUTION_BOARD',
    width: 140,
    height: 65,
    defaultVoltage: 380,
    defaultNominalCurrent: 5,
    defaultManufacturer: 'Schneider',
    defaultPartNumber: 'PM5300',
    iconType: 'multimeter',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'V_Sens' },
      { id: 'p_out', type: 'out', x: 70, y: 65, label: 'RS485' },
    ],
  },

  // CONEXÃO & ATERRAMENTO
  {
    id: 'sym_regua_bornes',
    category: 'CONEXAO',
    name: 'Régua de Terminais / Bornes',
    shortDescription: 'Bloco de Terminais Mola / Parafuso Sak',
    iecCode: 'IEC 60617-03-02',
    tagPrefix: 'XT',
    defaultCategory: 'DISTRIBUTION_BOARD',
    width: 140,
    height: 55,
    defaultVoltage: 380,
    defaultNominalCurrent: 32,
    defaultManufacturer: 'Phoenix Contact',
    defaultPartNumber: 'UT 4',
    iconType: 'terminal',
    ports: [
      { id: 'p_in', type: 'in', x: 70, y: 0, label: 'Cabo Interno' },
      { id: 'p_out', type: 'out', x: 70, y: 55, label: 'Cabo Externo' },
    ],
  },
  {
    id: 'sym_aterramento_pe',
    category: 'ATERRAMENTO',
    name: 'Barra de Terra Equipotencial BEP',
    shortDescription: 'Condutor PE / Aterramento Geral NBR 5410',
    iecCode: 'IEC 60617-02-15',
    tagPrefix: 'BEP',
    defaultCategory: 'BUSBAR',
    width: 200,
    height: 20,
    defaultVoltage: 0,
    defaultNominalCurrent: 400,
    defaultManufacturer: 'Termocobre',
    defaultPartNumber: 'Barra PE 30x5mm',
    iconType: 'ground',
    ports: [
      { id: 'p_g1', type: 'bus', x: 40, y: 20, label: 'PE1' },
      { id: 'p_g2', type: 'bus', x: 100, y: 20, label: 'PE2' },
      { id: 'p_g3', type: 'bus', x: 160, y: 20, label: 'PE3' },
    ],
  },
];
